
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:206 (message)"
      - "CMakeLists.txt:7 (project)"
    message: |
      The target system is: Android - 1 - armv7-a
      The host system is: Windows - 10.0.22621 - AMD64
...
